debug: false

spring:
  application.name: pricer-tgbot
  output.ansi.enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/pricer
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties.hibernate.format_sql: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: ERROR
  file:
    path: ./logs
    max-size: 10MB
    total-size-cap: 100MB
    max-history: 5

bot:
  token: ${TGBOT_PRICER_TOKEN}